config/routes.rb
Rails.application.routes.draw do
  resources :mies

end

app/models/my.rb
class My < ActiveRecord::Base
end

app/controllers/application_controller.rb
#:wq


class Test;end

class Test2;end
class Test12;end

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mies_controller.rb
class MiesController < ApplicationController
  before_action :set_my, only: [:show, :edit, :update, :destroy]

  # GET /mies
  # GET /mies.json
  def index
    @mies = My.all
  end

  # GET /mies/1
  # GET /mies/1.json
  def show
  end

  # GET /mies/new
  def new
    @my = My.new
  end

  # GET /mies/1/edit
  def edit
  end

  # POST /mies
  # POST /mies.json
  def create
    @my = My.new(my_params)

    respond_to do |format|
      if @my.save
        format.html { redirect_to @my, notice: 'My was successfully created.' }
        format.json { render :show, status: :created, location: @my }
      else
        format.html { render :new }
        format.json { render json: @my.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mies/1
  # PATCH/PUT /mies/1.json
  def update
    respond_to do |format|
      if @my.update(my_params)
        format.html { redirect_to @my, notice: 'My was successfully updated.' }
        format.json { render :show, status: :ok, location: @my }
      else
        format.html { render :edit }
        format.json { render json: @my.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mies/1
  # DELETE /mies/1.json
  def destroy
    @my.destroy
    respond_to do |format|
      format.html { redirect_to mies_url, notice: 'My was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my
      @my = My.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_params
      params.fetch(:my, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mies_helper.rb
module MiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mies/_form.html.erb
<%= form_for(@my) do |f| %>
  <% if @my.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@my.errors.count, "error") %> prohibited this my from being saved:</h2>

      <ul>
      <% @my.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mies/edit.html.erb
<h1>Editing My</h1>

<%= render 'form' %>

<%= link_to 'Show', @my %> |
<%= link_to 'Back', mies_path %>

app/views/mies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mies.each do |my| %>
      <tr>
        <td><%= link_to 'Show', my %></td>
        <td><%= link_to 'Edit', edit_my_path(my) %></td>
        <td><%= link_to 'Destroy', my, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My', new_my_path %>

app/views/mies/new.html.erb
<h1>New My</h1>

<%= render 'form' %>

<%= link_to 'Back', mies_path %>

app/views/mies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_my_path(@my) %> |
<%= link_to 'Back', mies_path %>